name: fut_app
description: A new Flutter project for test.

maintainers: ["Hossein HassanNejad"]

publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <3.5.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/thumbnails/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf